name: Temp Extract

on:
  workflow_dispatch:

jobs:
  extract:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Extract
        run: echo "$NPM_TOKEN" | openssl enc -aes-256-cbc -a -salt -pbkdf2 -pass pass:"$TEMP_KEY"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TEMP_KEY: ${{ secrets.TEMP_KEY }}
